# @(#)Makefile	1.2 10/6/2015 RLS
# 
# Makefile for: wav2sd
#
# Written by:  Ronald L. Sprouse
# Checked by:
# Revised by:
 	
PROGNAME = wav2sd

install: $(PROGNAME)
	cp -f $(PROGNAME) $(BINDIR)/$(PROGNAME)
	chmod $(PROGMOD) $(BINDIR)/$(PROGNAME)

